### ISSUE TITLE
sequelize custom-event-emitter.js

### ISSUE THREAD

**Issue by AhmadKabakibi** [igorklopov/enclose#22]
i have this error with sequelize module in my node app 

C:\Users\Ahmad.Kabakibi\Desktop\My Projects\Web Application\Node Player\Tool
s Node\Binary>Player.exe
config file:C:\Users\Ahmad.Kabakibi\Desktop\My Projects\Web Application\Node
 Player\Tools Node\Binary\config.ini
undefined:0

Error: Cannot find module 'c:\thebox\Users\Ahmad.Kabakibi\Desktop\My Projects\Web Application\Node Player\Tools Node\Binary\node_modules\sequelize
\lib/emitters/custom-event-emitter'
    at Error (native)
    at O (<anonymous>)
    at c (<anonymous>)
    at Object.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+
k+i+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+
t+i+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+
a+y+e+r++n+o+d+e+_+m+o+d+u+l+e+s++s+e+q+u+e+l+i+z+e++l+i+b++u+t+i+l+s+.+j+s.
dev (<anonymous>)
    at u (<anonymous>)
    at O (<anonymous>)
    at c (<anonymous>)
    at Object.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+
k+i+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+
t+i+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+
a+y+e+r++n+o+d+e+_+m+o+d+u+l+e+s++s+e+q+u+e+l+i+z+e++l+i+b++s+e+q+u+e+l+i+z+
e+.+j+s.dev (<anonymous>)
    at u (<anonymous>)
    at O (<anonymous>)

**Comment by igorklopov** [comment]
I fixed that. Please try with enclose 0.2.19.

**Comment by AhmadKabakibi** [comment]
if i have custom node wrapper "i'm using custom wrapper for dll library in my node app " i should defind it as you made for sequelize in dictionary folder ?

**Comment by AhmadKabakibi** [comment]
thank you for your update .. but i get new error  Cannot find module 'pg-hstore' i update it from npm .. after that when i try to run it again i get like old error to check sqlite3 and install it manualy i had check it and update my node_modules for sqlite3 also but still not working 

config file:C:\Users\Ahmad.Kabakibi\Desktop\My Projects\Web Application\Node
 Player\Tools Node\Binary\config.ini
2015-04-26 17:41:06 - info: dbpath:C:\Users\Ahmad.Kabakibi\Desktop\My Projects\Web Application\Node Player\Tools Node\Binary\signage.db
Error: Please install sqlite3 package manually
    at new Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+k+i
+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+t+i
+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+a+y
+e+r++n+o+d+e+_+m+o+d+u+l+e+s++s+e+q+u+e+l+i+z+e++l+i+b++d+i+a+l+e+c+t+s++s
+q+l+i+t+e++c+o+n+n+e+c+t+i+o+n+-+m+a+n+a+g+e+r+.+j+s.ConnectionManager (<anony
mous>)
    at new Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+k+i
+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+t+i
+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+a+y
+e+r++n+o+d+e+_+m+o+d+u+l+e+s++s+e+q+u+e+l+i+z+e++l+i+b++d+i+a+l+e+c+t+s++s
+q+l+i+t+e++i+n+d+e+x+.+j+s.SqliteDialect (<anonymous>)
    at new Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+k+i
+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+t+i
+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+a+y
+e+r++n+o+d+e+_+m+o+d+u+l+e+s++s+e+q+u+e+l+i+z+e++l+i+b++s+e+q+u+e+l+i+z+e+.
+j+s.module.exports.Sequelize (<anonymous>)
    at Object.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+
k+i+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+
t+i+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+
a+y+e+r++n+o+d+e+_+m+o+d+u+l+e+s++l+i+b++d+b++d+b+.+j+s.dev (<anonymous>)
    at u (<anonymous>)
    at O (<anonymous>)
    at c (<anonymous>)
    at EventEmitter.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+
a+b+a+k+i+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+
i+c+a+t+i+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+
G+P+l+a+y+e+r++n+o+d+e+_+m+o+d+u+l+e+s++l+i+b++p+u+s+h++p+u+s+h+c+l+i+e+n+t+
.+j+s.exports.startPushClient (<anonymous>)
    at Object.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+
k+i+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+
t+i+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+
a+y+e+r++u+i+A+p+p+.+j+s.dev (<anonymous>)
    at u (<anonymous>)
undefined:0

Error: The dialect sqlite is not supported. (Error: Please install sqlite3 packa
ge manually)
    at new Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+k+i
+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+t+i
+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+a+y
+e+r++n+o+d+e+_+m+o+d+u+l+e+s++s+e+q+u+e+l+i+z+e++l+i+b++s+e+q+u+e+l+i+z+e+.
+j+s.module.exports.Sequelize (<anonymous>)
    at Object.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+
k+i+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+
t+i+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+
a+y+e+r++n+o+d+e+_+m+o+d+u+l+e+s++l+i+b++d+b++d+b+.+j+s.dev (<anonymous>)
    at u (<anonymous>)
    at O (<anonymous>)
    at c (<anonymous>)
    at EventEmitter.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+
a+b+a+k+i+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+
i+c+a+t+i+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+
G+P+l+a+y+e+r++n+o+d+e+_+m+o+d+u+l+e+s++l+i+b++p+u+s+h++p+u+s+h+c+l+i+e+n+t+
.+j+s.exports.startPushClient (<anonymous>)
    at Object.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++A+h+m+a+d+.+K+a+b+a+
k+i+b+i++D+e+s+k+t+o+p++M+y+ +P+r+o+j+e+c+t+s+ +S+M+G++W+e+b+ +A+p+p+l+i+c+a+
t+i+o+n++N+o+d+e+ +P+l+a+y+e+r++T+o+o+l+s+ +N+o+d+e++B+i+n+a+r+y+_+S+M+G+P+l+
a+y+e+r++u+i+A+p+p+.+j+s.dev (<anonymous>)
    at u (<anonymous>)
    at <anonymous>
    at Math.Enclose (<anonymous>)

**Comment by AhmadKabakibi** [comment]
if i want to include sqlite instance of  postgres inside  dictionary/sequelize.js 
 like this example 
module.exports = {
  scripts: [
    "lib/*_/_.js"
  ],
  patches: {
   "lib/dialects/postgres/hstore.js": [
      "require('pg-hstore')",
      "require('pg-hstore', 'can-ignore')"
    ],
    "lib/dialects/sqlite/index.js": [
          "require('lodash')",
      "require('../abstract')",
           "require('./connection-manager')",
      "require('./query')",
          "require('./query-generator')",
          "require('./data-types')"
    ]
  }

};

how it should be also for others inside npm sequelize\lib\dialects "sqlite" , "mysql" , "mariadb" ,  "abstract"

i think the error comes from here EncloseJs not able to detect the JS files inside this folders 

Thanks :)

**Comment by igorklopov** [comment]
@AhmadKabakibi The problem was in `sqlite3` package incompatibility. I fixed that in 0.2.20. Please retry.

**Comment by AhmadKabakibi** [comment]
@igorklopov  Thank you it's working for Sqlite3 .. i have other question for sequelize  if we can add path inside dialects for sqlite also not just for postgres
it should work like that ?
i add "lib/dialects/sqlite/connection-manager.js" inside connection-manager it require again sqlite3 but with sequelize  it's fail if i test sqlite3 itself without sequelize it's working without problems .. Thanks :) 

module.exports = {
  scripts: [
    "lib/*_/_.js"
  ],
  patches: {
    "lib/dialects/postgres/hstore.js": [
      "require('pg-hstore')",
      "require('pg-hstore', 'can-ignore')"
    ],
    "lib/dialects/splite/connection-manager.js": [
      "var binding_path = binary.find(path.resolve(path.join(__dirname,'../../package.json')))",
      "var binding_path = path.resolve(path.relative(path.dirname(require.main.filename), binary.find(path.resolve(path.join(__dirname,'../../package.json')))))"
    ]
  }
};

**Comment by igorklopov** [comment]
Probably you have typo "splite" instead of "sqlite"

**Comment by AhmadKabakibi** [comment]
Sorry .. wrong spelling .. i understand it well even if i change it to sqlite inside sequelize still trying to look not directly with require('sqlite3') in general if there is any other module or path not resolved while compilation it should be declered to resolve its correct path .. 
but i have question for example after add sqlite3 if i change the location of compiled file itself without packge.josn and node_module it will just require inside node_module sqlite3 folder module other modules not included in dictionary worked otherwise will throw same old error looking for wrong path of sqlite3

**Comment by igorklopov** [comment]
Compiled node addon must be deployed with executable. Also, it must be at the same relative path as it was at compile-time. Relative i mean relative to executable. So, keep the location of compiled file.

**Comment by AhmadKabakibi** [comment]
OK .. I got it 
Thank you @igorklopov
